### ISSUE TITLE
OpenPdC Configuration Saving

### ISSUE THREAD

**Issue by Vtern** [GridProtectionAlliance/openPDC#10]
Hallo,

I would like to know if the Openpdc permits to save its configuration including PMUs attached, Adapter achieved, Alarms and so on. This could be useful both due to the recurrent re installation of the nightly build versions and for instance to re-install on another workstation.

Could you explain it is possible and how?

Thanks

V

**Comment by ritchiecarroll** [comment]
Primary configuration for the openPDC is the openPDC.exe.config file and the associated database. With these two items can easily transfer an existing configuration between machines and persist configuration between installs.

Note that the installer will manage persisting the configuration between upgrades.

Thanks,
Ritchie
