### ISSUE TITLE
Archiving data using Historian Instance

### ISSUE THREAD

**Issue by anudeepm** [GridProtectionAlliance/openPDC#100]
Hi,

I have connected four PMUs and I am able to monitor/read data from the openPDC console. But, when I archive the data to read it from historian view application in openPDC, I see only NaN values. 

My final objective is to read the historical measurements through MySQL database. I have created a new output historian instance as described in http://openpdc.codeplex.com/discussions/571880 

Please find attached the open-historian-instance-configuration screenshot, errorlog text file, and the CSV data file after exporting from historian view application
![manage_historian_instances](https://user-images.githubusercontent.com/32944226/31800147-03d1da7e-b4fc-11e7-85ee-6b26c637f1d0.JPG)
[ErrorLog.txt](https://github.com/GridProtectionAlliance/openPDC/files/1400411/ErrorLog.txt)
[freqHistorian.xlsx](https://github.com/GridProtectionAlliance/openPDC/files/1400420/freqHistorian.xlsx)

--
Thanks,
Anudeep

**Comment by ritchiecarroll** [comment]
Here was a similar discussion:
http://discussions.gridprotectionalliance.org/t/ado-output-adapter-error-failed-to-initialize-adapter-not-connecting-to-mysql-database/152

Per this outcome, perhaps you should double check your MySQL Connector.NET version number.

I am going to close this for now, feel free to reopen if issue still occurs.
