### ISSUE TITLE
Access to STAT using Grafana

### ISSUE THREAD

**Issue by logiclabsrl** [GridProtectionAlliance/openPDC#102]
Hi,
I'm using Grafana to plot data collected by OpenHistorian. With PPA all works fine while I'm not able to access to STAT configuring Grafana Data Source url as http://_ip_address_:6356/api/grafana/ 

openHistorian.exe.config seems to be configured correctly.

Any support will be greatly appreciated.
Thanks
Daniele

**Comment by ritchiecarroll** [comment]
These settings work for me:

![image](https://user-images.githubusercontent.com/9202752/34048721-ca662138-e182-11e7-8c4c-5b4703ecf304.png)

Do you happen to be running in debug mode or is this from an installed version?

Thanks,
Ritchie

**Comment by logiclabsrl** [comment]
My mistake was to configure HTTP Settings / Access : direct.
With Proxy, it works! 

Thanks
Daniele
