### ISSUE TITLE
Compatible SQL Server version

### ISSUE THREAD

**Issue by mlbeauchemin** [GridProtectionAlliance/openPDC#108]
We are looking to upgrade to openPDC v2.5. What version of SQL Server is required? Does it matter? I can't seem to find definite requirements for this in the documentation. Specifically, is v2.5 compatible with SQL Server 2016 with Always On Availability Groups?

**Comment by ritchiecarroll** [comment]
Never directly tested "Always On Availability Groups", however, 2016 SQL Server should be just fine...

**Comment by mlbeauchemin** [comment]
Thanks for the quick response!
