### ISSUE TITLE
not able to receive data from PMU

### ISSUE THREAD

**Issue by pra12eep** [GridProtectionAlliance/openPDC#115]
Dear All, I have setup the openPDC system in the lab and I was able to get the output stream of 2 PMU in openPDC after checking them through PMU Connection Tester. 
After few days I was trying to connect the 3rd PMU and system showed a message that "Application is currently disconnected from service" and I am not able to get the out of any PMU in openPDC. 
 I have screenshots of the error msgs which i trying to upload but system is giving error that we can't process that file.

Kindly guide me.

**Comment by StephenCWills** [comment]
The openPDC Manager typically displays that message when the service is offline. I recommend checking the Windows Services Manager to determine the current state of the openPDC service.

https://www.thewindowsclub.com/open-windows-services

**Comment by pra12eep** [comment]
its working now.
Thank you Stephen!
