### ISSUE TITLE
Identification Error 

### ISSUE THREAD

**Issue by iradevic** [GridProtectionAlliance/openPDC#116]
Hello,

I am facing the identification issue when running openPDCManager. Please, find the screenshot of the issue attached. I would kindly ask for your opinion about the possible solution. 

Thank you

Isidora

![openpdc_identification_error](https://user-images.githubusercontent.com/33296140/50903098-0dd23d80-141d-11e9-9b64-451c97a3aa5a.JPG)

**Comment by StephenCWills** [comment]
Hello Isidora,

I just have a few questions that may help to pin down the resolution.

1. Is this a clean install of the openPDC, or has it been upgraded?
2. Does the NodeID field in the `openPDCManager.exe.config` file match the NodeID field in `openPDC.exe.config`?
3. Are you using MySQL for your configuration database?

Thanks,
Stephen

**Comment by iradevic** [comment]
Hello Stephen,

Thank you for your prompt reply.
These are answers:
1. This is a clean install of the openPDC
2. NodeID fields match
3. Yes, I am using MySQL

I hope the answers filter some solution! 

Thanks,

Isidora

**Comment by StephenCWills** [comment]
This issue has been reported to occur with certain versions of the MySQL Connector/NET driver. The 6.9.12 version of MySQL Connector/NET (available by clicking the "Looking for previous GA releases?" link) is the one that works best with our software.

**Comment by iradevic** [comment]
Thank you, problem solved in the way you suggested!
