### ISSUE TITLE
API to read data from local archive *.d data

### ISSUE THREAD

**Issue by Xinya-Li** [GridProtectionAlliance/openPDC#125]
For OpenHistorian, there is a way to read data through a API as described in
https://github.com/GridProtectionAlliance/openHistorian/blob/master/Source/Documentation/wiki/openHistorian_Documentation.md
"Open Archive" from Historian Trending Tool did a same thing using the connection settings.

Is there a similar way to do that for openPDC archive data (*.d)? The "Open Archive" in Historian Trending Tool in openPDC is different by targeting archive location directly.

Thank you very much

**Comment by ritchiecarroll** [comment]
Sure. Looks at the source for this tool:

https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Tools/HistorianView/MainWindow.xaml.cs#L600

It opens .D files and queries and visualizes the data using the ArchiveReader class:

https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Historian/Files/ArchiveReader.cs

Thanks,
Ritchie
