### ISSUE TITLE
OpenPDC Manager 2.7.4.0 - Error during starting up the programm

### ISSUE THREAD

**Issue by tmarecek** [GridProtectionAlliance/openPDC#128]
Hello,

I have instalation of OpenPDC Manager v 2.7.4.0. on Microsoft Windows Server 2016 Standard and following error message is shown up when I want to open OpenPDC Manager:

Error details: Value cannot be null.
Parameter name: value

 It seems, that output and input streams are working fine. Do you have any suggestion what could cause this behaviour? 

Thank you vey much and have a nice day.

**Comment by tmarecek** [comment]
![OpenPDC - error](https://user-images.githubusercontent.com/43998061/70909042-e7455b00-200c-11ea-9d44-040254b81a6a.png)

**Comment by ritchiecarroll** [comment]
Commonly this is because you don't have rights to the database openPDC is using. Check the connection string for the openPDC (in the openPDC.exe.config) and see if you have rights to access the specified database.

**Comment by ritchiecarroll** [comment]
Going to close this one - let me know if you still have issues.

Thanks!
Ritchie
