### ISSUE TITLE
REDHAT/CENTOS INSTALLATION OF OPENPDC

### ISSUE THREAD

**Issue by Vtern** [GridProtectionAlliance/openPDC#13]
Hallo,

are you available to provide also a comprehensive rpm file containing all the needed libraries to work under RedHat/Centos 6.X Linux distribution for testing purposes?  

Best Regards

**Comment by arkrohne** [comment]
As openPDC on Linux is a beta at this point, we don't currently provide any precompiled packages for any distribution. However, we are looking into providing those in the near future.

**Comment by cosimopis** [comment]
Hi guys,

are there any advances in openpdc deployment in Linux environment? 

Kind Regards

**Comment by ritchiecarroll** [comment]
Try the latest release:
https://github.com/GridProtectionAlliance/openPDC/releases/tag/v2.9.148
