### ISSUE TITLE
Historian Playback error

### ISSUE THREAD

**Issue by KoltonFoster** [GridProtectionAlliance/openPDC#132]
Issue with pulling PMU data from Historian playback. Program crashes when saving data. Screen shot and windows events included. Thanks in advance. 

PRogram error

Historianplaybackutility has stoppeed working. -a problem caused the prgoram to stop working correctly. Windows will close the program and notify you if a solution is found. 

--terminal last message
Transmissions complete (0 errors)

WINDOWS EVENT VIEWER

Event 1026

Application: HistorianPlaybackUtility.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at GSF.Threading.SharedTimer.set_Enabled(Boolean)
   at GSF.Communication.FileClient.Disconnect()
   at GSF.Communication.ClientBase.Dispose(Boolean)
   at GSF.Communication.FileClient.Dispose(Boolean)
   at System.ComponentModel.Component.Dispose()
   at HistorianPlaybackUtility.Main.Process(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event error 1000

Faulting application name: HistorianPlaybackUtility.exe, version: 2.3.56.0, time stamp: 0x5bdc6fa2
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24545, time stamp: 0x5e0eb6bd
Exception code: 0xe0434352
Fault offset: 0x000000000000b87d
Faulting process id: 0x58d8
Faulting application start time: 0x01d62243bc0928a1
Faulting application path: C:\Program Files\openPDC\HistorianPlaybackUtility.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: ee7070c5-8e37-11ea-9b46-64006a5a97e0

Fault bucket 3251578468, type 535715211
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: HistorianPlaybackUtility.exe
P2: 2.3.56.0
P3: 5bdc6fa2
P4: GSF.Core
P5: 2.3.56.0
P6: 5bdc6f4b
P7: cc5
P8: 18
P9: System.ObjectDisposedException
P10: 

error 1001

Attached files:
C:\Users\ePDC Operator\AppData\Local\Temp\WER54F.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\ePDC Operator\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_HistorianPlaybac_4ee989844cc9fc156bc8bca72ea5d845ebe5888e_5ffa2109

Analysis symbol: 
Rechecking for solution: 0
Report Id: ee7070c5-8e37-11ea-9b46-64006a5a97e0
Report Status: 0
![HSP Utility stopped working](https://user-images.githubusercontent.com/64805674/81003502-9a71ed80-8e10-11ea-8cbd-4a495c00684f.PNG)
![HSP Utility stopped working](https://user-images.githubusercontent.com/64805674/81003525-a2319200-8e10-11ea-93a9-3db58b6f39ab.PNG)

**Comment by ritchiecarroll** [comment]
Fixed with: https://github.com/GridProtectionAlliance/gsf/commit/3346f29c1956adcdac937c747b44ccbc9ae9bb10

This should be available in next nightly build of openPDC - usually builds around midnight Eastern time. You can download from here tomorrow:

http://www.gridprotectionalliance.org/nightlybuilds/openPDC/Beta/Synchrophasor.Installs.zip
