### ISSUE TITLE
Ubuntu distro to install openPDC

### ISSUE THREAD

**Issue by Milozpp** [GridProtectionAlliance/openPDC#137]
Hi to all,
i'am trying to install openPDC sw in my distro ubuntu 16.04(i used different version to fix my problems) but i found al lot of errors(many of this are equall to many other i read in other issues) where the first is the impossibility to run openPDC.exe after i launched the bash command to build all the envirorment (sudo bash install-openPDC.sh). It seems the bash command don't complete his esecution well. some of this errors are:
     - cp: cannot stat ‘openPDC/Build/Output/Mono/Applications/openPDC/*’: No such file or directory
     - mkdir: cannot create directory ‘/opt/openPDC/Database Scripts’: File exists
     - cp: cannot stat ‘gsf/Build/Output/Mono/Tools/MonoGenCert/MonoGenCert.exe’: No such file or directory 
     Creating transport layer security keys and certificates...
     Cannot open assembly 'MonoGenCert.exe': No such file or directory.
     Installing GEP Subscription Tester...
     Applying default POSIX configuration to openPDC installation...
     openPDC installation complete. To start application, run:
     sudo mono /opt/openPDC/openPDC.exe -RunAsConsole"   
However when i try to lanch the command  sudo mono /opt/openPDC/openPDC.exe -RunAsConsole the shell reports :no such file or directory error.
    
I have read the log errors file and it reports a lot of errors like:
        Collections/FileBackedLookupTable.cs(642,33): error CS1525: Unexpected symbol `(', expecting `,', `;', or `='
	Collections/FileBackedLookupTable.cs(661,13): error CS1520: Class, struct, or interface method must have a return type
	Collections/FileBackedLookupTable.cs(663,15): error CS1519: Unexpected symbol `try' in class, struct, or interface member declaration
	Collections/FileBackedLookupTable.cs(664,13): error CS9010: Primary constructor body is not allowed
	Collections/FileBackedLookupTable.cs(676,17): error CS1519: Unexpected symbol `catch' in class, struct, or interface   member declaration 
         ServiceClient.cs(24,7): error CS0246: The type or namespace name `GSF' could not be found. Are you missing an assembly reference?
        ServiceClient.cs(25,7): error CS0246: The type or namespace name `GSF' could not be found. Are you missing an assembly reference?
       ServiceClient.cs(26,7): error CS0246: The type or namespace name `GSF' could not be found. Are you missing an assembly reference?
and many other errors like expression evaluator not found.

I tried also to digit some commands post in other issues to fix the problems but the errors remains anyway. My questios is :
is ubuntu a right OS where install openPDC sw? I read and executed every command found in the guide: so, could someone helps me to fix the problems? TY

//Milo

**Comment by ritchiecarroll** [comment]
Try the latest release:
https://github.com/GridProtectionAlliance/openPDC/releases/tag/v2.9.148
