### ISSUE TITLE
outputstream micro-interruptions in OpenPDC/OpenHist 

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#138]
Dear Colleauges,

sometimes we have some interruptions in outputstream our OpenPDC, I would like to deepen the root causes. May you provide some indications how to deepen the issue it i.e. exploring the logs?
Any suggestions?

Thanks,

Cosimo

**Comment by ritchiecarroll** [comment]
Try the latest release:
https://github.com/GridProtectionAlliance/openPDC/releases/tag/v2.9.148
