### ISSUE TITLE
OPEN PDC INSTALLATION ON WINDOWS SERVER 2008 R2 64 BIT 

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#14]
Hallo,

can OpenPdC be installed successfully on WINDOWS SERVER 2008 R2 64 BIT?

Regards

**Comment by arkrohne** [comment]
Yes, Windows Server 2008 R2 64 bit is a supported platform for openPDC.

**Comment by cosimopis** [comment]
Thanks Andrew!
