### ISSUE TITLE
How can I export the openPDC manager's  data as a CSV file

### ISSUE THREAD

**Issue by deymaitreyee** [GridProtectionAlliance/openPDC#145]
I am able to connect our upmus through openPDC manager. I can see the values in the graph real time measurements. But whenever I tried to see the previous data won't be able to do that. I have seen couple of Q&A but are not related exactly what I want.

![image](https://user-images.githubusercontent.com/37809402/154513820-36f4258d-6e0b-4c3f-addd-460975d9c38b.png)

Any help will highly appreciable.
Maitreyee

**Comment by ritchiecarroll** [comment]
This depends on if you configured openPDC to archive data when you set it up.

One easy way is to simply install the openHistorian (https://github.com/GridProtectionAlliance/openHistorian) then connect openHistorian to openPDC and use the openHIstorian web interface to export to CSV or COMTRADE.

Thanks,
Ritchie

**Comment by deymaitreyee** [comment]
Thanks Ritchie for you reply.

When I configured the openPDC, I have chosen PPA as historian.

I have installed openHistorian manager but couldn't able to link it with openPDC.
Can you help me further on this?

Many thanks
Maitreyee

**Comment by deymaitreyee** [comment]
Hi 

Additionally, now i have managed to synch the OpenHistorian with openPDC but can't getting any graph measurements. see below pic.
![image](https://user-images.githubusercontent.com/37809402/155161802-0f790816-e6f3-442a-83b3-bdd9564ef714.png)


How can i see the same graph measurements?
How can I get the data as a csv file?

Many thanks
Maitreyee

**Comment by ritchiecarroll** [comment]
Can you enumerate the steps you followed to connect openHistorian to openPDC?

I would expect something like following:

_Note: You may need to delete existing `PDC` connection before following these steps._

1) From within the openHistorian Manager, go to "Inputs > Subscription Based Inputs > Create Internal Subscription"
2) Enter `PDC` in the "Acronym" field
3) Enter `localhost` in the "Hostname" field
4) Enter `7165` in the "Port" field
5) Uncheck "Use Source Prefix"
6) Click "Next" button
7) Click "Save" button

One this is working properly, you can browse to http://localhost:8180/ to trend and export data to a CSV.

Thanks,
Ritchie
