### ISSUE TITLE
# openPDC and openHistorian configuration 

### ISSUE THREAD

**Issue by Khwbas** [GridProtectionAlliance/openPDC#157]
Hi experts,
                I am new to openPDC and openHistorian synchrophasor. I have the following cases for which I would like to used openPDC and openHistorian.
1. I have simulated network in RTDS and also placed PMU (enable IEEEC37.118 synchrophasor protocol compatible). I would like to archive the data and visualize it.
2. What is the specific application difference between openPDC and openHistorian?
3. Is openHistorian can be operate alone to archive data and visualization?
4. should I install openPDC and openHistorian both to fulfil point 1 above.

I have tested the connection by connecting the PMU connection tester and works well, showing phasor curves. But, I am not able to establish the openHistorian connection, as it shows PMU grey or red color fluctuates but when I create disturbance in network (simulation) I can see frequency curves. Please guide me to establish the openHistorian connection with PMU showing green color?

Thanks and regards,
Khwrwmdao Basumatary

**Comment by StephenCWills** [comment]
Hi Khwrwmdao,

The main difference between openPDC and openHistorian has to do with their primary function. openPDC is intended for concentration of real-time streaming data, meaning that it's well suited for routing, real-time analysis, and protocol translation. openHistorian is intended for archival making it well suited for data storage, data visualization, and post-event analysis.

In the scenario you describe, it should be sufficient to set up only openHistorian without openPDC. openHistorian by itself should be fully capable of connecting directly to your PMUs for archival and visualization.

openHistorian and PMU Connection Tester actually share much of the same code for connecting to PMU devices. If you were able to successfully connect to the device using the PMU Connection Tester, the same connection should typically work for openHistorian. In this case, I would recommend exporting a PmuConnection file by navigating to `File > Connection > Save...` in the PMU Connection Tester, then using the input wizard in openHistorian Manager to import the PmuConnection file. This will match openHistorian's settings with the PMU Connection Tester's, hopefully ruling out any mistakes you might have made during configuration of the connection in openHistorian.

**Comment by Khwbas** [comment]
In addition, In the RTDS pmu is named PMU, I changed it to the AADHRIT_PMU in openHistorian. Does this might impact while communication between openHistorian and PMU in RTDS ?

**Comment by StephenCWills** [comment]
It seems there is nothing wrong with the communications here. openHistorian is receiving the data, and you are able to visualize it using all of openHistorian's tools.

You may notice at the bottom-left corner in your very first screenshot, the `Time` field indicates that the simulator is sending data with timestamps from 2011. You mentioned this later as well when displaying data using the `Trend / Export Measurements` page of the web manager. What appears to be happening on the Graph Measurements page of openHistorian Manager is the simulator's timestamps are being validated against those of `TESTDEVICE` and are found to be much too old to fit into the time window defined by the lag time and lead time specified under Display Settings. You should try disabling `TESTDEVICE` to see if the page starts behaving better. You may also need to review the Display Settings to ensure that it's not attempting to use your computer's local clock as real time.

For the `Trend / Export Measurements` page, I'm not entirely sure what you mean by not being able to adjust the time window. I guess you used the mouse wheel over the graph to arrive at the appropriate time, but it should also have been possible to simply change the dates and time entered into those text boxes. There isn't a way to automatically fit data into the graph window. You'll need to have an idea of what time range you're looking into when you go to export data from the archive.

Renaming the PMU in openHistorian shouldn't cause any problems so long as the `Access ID` (aka `ID Code`) of that PMU is unique within the stream. If it's not, then there won't be any identifying characteristics of the PMU that openHistorian can use to disambiguate the data that it's receiving.

**Comment by clackner-gpa** [comment]
Since this is not an issue or bug in the code We will close this. For further discussion on this topic or any other questions you may have feel free to post on our forum (https://discussions.gridprotectionalliance.org/).
