### ISSUE TITLE
Error adding pmu into output stream

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openPDC#17]
error when add PMU into "Concentrator output streams" 

![openpdc_error_newstream](https://cloud.githubusercontent.com/assets/18598157/16587354/8f0f3776-42ca-11e6-830a-eadc1114ae47.JPG)
[opnepdc error.txt](https://github.com/GridProtectionAlliance/openPDC/files/347892/opnepdc.error.txt)

available to provide more details.

Pietro

**Comment by pietropau** [comment]
2.2.69.0

Pietro

**Comment by ritchiecarroll** [comment]
MySQL?

**Comment by pietropau** [comment]
Yes mysql 5.7.13.

**Comment by ritchiecarroll** [comment]
OK, will try to replicate....

**Comment by StephenCWills** [comment]
Hi Pietro - have you deleted a historian from your system? You can fix the historian IDs of your measurements by editing the configuration of your device, selecting the "Select Historian" option from the Historian dropdown on the Device, and saving the change.

Thanks,
Stephen

**Comment by pietropau** [comment]
Hi Stephen, I confirm that we had canceled a historian instance.

Ciao
Pietro

**Comment by ritchiecarroll** [comment]
Unhandled exception corrected with fcfac8476cd42abb946e82eba44f161630fb89bd
