### ISSUE TITLE
README's Wiki URL goes to a Permission Denied Page

### ISSUE THREAD

**Issue by ajstadlin** [GridProtectionAlliance/openPDC#19]
The **wiki** hyperlink in the 5th bullet of the Documentation and Support section goes to the following Permission Denied Page.  If that link is going to be the wiki for this project, it should be made readable to the public.

[https://gridprotectionalliance.org/wiki/doku.php?id=openpdc:overview](https://gridprotectionalliance.org/wiki/doku.php?id=openpdc:overview)

The Wiki URL in the current openPDC GitHub repository is:

[https://github.com/GridProtectionAlliance/openPDC/wiki](https://github.com/GridProtectionAlliance/openPDC/wiki)

//AJ

**Comment by arkrohne** [comment]
The wiki has been opened.
