### ISSUE TITLE
openPDCConsole in Windows Command Line not recognizing IPv4

### ISSUE THREAD

**Issue by ajstadlin** [GridProtectionAlliance/openPDC#20]
**openPDCConsole Version 2.2.70** does not recognize IPv4 in the Windows Command Line.  For example:

`C:\GPA.Apps\openPDC>openPDCConsole.exe -server="openpdc-pi3:8500; interface=0.0.0.0"`
or
`C:\GPA.Apps\openPDC>openPDCConsole.exe -server="openpdc-pi3:8500" -interface="0.0.0.0"`

Fail with the result:

`Exception during connection attempt: IP address mismatch: unable to find an IPv6 address for "openpdc-pi3"`

It also fails if I substitute the IPv4 address for the server host name.  e.g.:  server=10.0.0.17:8500 ...

However, it works OK if I do not use the command line parameters And I set the connection string in the **openPDCConsole.exe.config** file:

`<add name="ConnectionString" value="Server=openpdc-pi3:8500; interface=0.0.0.0"
        description="Data required by the client to connect to the server."
        encrypted="false" />`

**Comment by ritchiecarroll** [comment]
What happens if you don't put a space between 8500; and interface?

**Comment by ajstadlin** [comment]
NO SPACE after the semi-colon Works!  I'll make sure the documentation update does not have a space!   

`openPDCConsole.exe -server="openpdc-pi3:8500;interface=0.0.0.0"`

THANKS!
//AJ
