### ISSUE TITLE
VERIFY QUALITY OF DATA RECEIVED

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#25]
Hi everyone,

How I can verify the quality of the data, for instance when a loss of samples or for instance if some PMU desynchronizations occur?

Many thanks,

Cosimo

**Comment by ritchiecarroll** [comment]
Have you turned the data quality reporting in the openPDC? From the openPDC Manager main menu, go to "Reporting / Completeness Reports" and enable this report to produce a daily quality report. You can also set this up to be e-mailed.

Thanks,
Ritchie

**Comment by cosimopis** [comment]
Thanks a lot Ritchie,

I will explore it.

**Comment by StephenCWills** [comment]
It appears the question was answered so I am closing the issue.
