### ISSUE TITLE
Retrieve data from PMU removed by OpenPDC

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#30]
Hi,

I recently removed a PMU in openPDC (which has an internal subcription with OpenHISTORIAN) and I immediately bring it back with a different name bothe for device and associated measurements. Is there a manner to retrieve data related to the old configuration? Obviously when I use Historian web manager I'm able to see only the new one device and hence new measurements...

Please let me know,

Kind regards,

Cosimo

**Comment by ritchiecarroll** [comment]
If you simply rename the the device, this will update measurements and this update will be reflected in historian.

It would be very challenging to remap new device points to the one that was deleted, but not impossible.
