### ISSUE TITLE
SEQUENCE CALCULATOR

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#31]
HI, 
I'm folowing the discussion "Wiki Link: [discussion:462636]" in order to implement a sequence calculator. 
I understood that the mapping I/O is 6by6 but from the output type I don't see a "sequence calculated type" so I used simple "Calculated type" (and specifically Current Magnitude and phase angle)...

![image](https://cloud.githubusercontent.com/assets/19221022/18739375/77de697a-80a3-11e6-8946-6ee1d3d6ba67.png)

Do you have any reference example?   

Thanks

Cosimo

**Comment by StephenCWills** [comment]
Hi Cosimo,

Sequence components are modeled as phasors, so it should be okay to use either the Voltage Magnitude and Voltage Phase Angle types or the Current Magnitude and Current Phase Angle types. Ultimately, the type is just metadata to help identify the measurement so you won't break anything if you pick Calculated Value, for instance. Downstream applications will be able to see the type you assign to the measurement, so I would recommend simply picking the type that seems most logical to you.

Unfortunately, we do not have a reference example as our sample data only includes positive sequence phasors.

Thanks,
Stephen
