### ISSUE TITLE
HARDWARE REQUIREMENTS

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#7]
Hallo,

Could you suggest what should be the hardware requirements to manage properly about 70 PMUs?

Thanks,

Cosimo

**Comment by ritchiecarroll** [comment]
Ignoring disk storage requirements, something like akin to the following would be more than sufficient:

Processor: 8 to 12 Cores @ 3.0 GHz or greater
Memory: 32 Gigabytes

You could likely get away with much less, but it is always nice to have breathing room.
