### ISSUE TITLE
Problem with timezone

### ISSUE THREAD

**Issue by chautran123** [GridProtectionAlliance/openPDC#93]
I have problem when change time zone of connect device in openPDC. When i set timezone of new Device in openPDC is "Select TimeZone", the timestamp in Monitoring Divice Output is 04:00:00 (example). But, when i set timezone to UTC+7-  Bangkok, Hanoi, Jakarta( My local zone) the timestamp in Monitoring Divice Output is 21:00:00, not look like my localtime in my computer. I don't know why. Please help!
Thank you!

**Comment by ritchiecarroll** [comment]
All date times in the openPDC are displayed in UTC
