### ISSUE TITLE
Trouble Archiving data using openPDC/openHistorian

### ISSUE THREAD

**Issue by sbasumal** [GridProtectionAlliance/openPDC#94]
Hi,

I am trying to use openHistorian to archive real time data from SEL 421 and I have the following two issues:

1. Can i not use openPDC and openHistorian at the same time to view real time data? Devices in one software turn 'red' from 'green' when i use the other.
![image](https://user-images.githubusercontent.com/29841115/27772398-94b7ab36-5f2f-11e7-907a-08c37ed09d48.png)

2. How do I actually archive the real time data? I have been able to successfully go this far. 
![image](https://user-images.githubusercontent.com/29841115/27772411-c4056d38-5f2f-11e7-99a9-375f3e52b536.png)

Thanks.

**Comment by StephenCWills** [comment]
Hi sbasumal,

1. Serial ports are exclusive resources, meaning that two separate pieces of software cannot use the same serial port at the same time. If you need to get the data into both applications, you can connect openPDC to the SEL-421 devices and then connect openHistorian to openPDC. The connection between openHistorian and openPDC can be established rather easily by using openHistorian Manager to create an internal subscription to port 6165.

2. On the `Device Configuration` page of the openHistorian Manager, there is a combo box labeled `Historian`. Using that combo box, you can select the destination archive for the data coming from that device. In the screenshots you provided before editing this issue, it looks like you had `PPA` selected as the destination archive, so the data that was plotted in your latest screenshot should already have been saved in the PPA archive. You can use the `Trend / Export Archived Data` page of the openHistorian Web Manager to plot or export archived data. That should allow you to verify whether the data has been successfully archived.

Thanks,
Stephen

**Comment by sbasumal** [comment]
Thanks, it worked. I re-installed the software and things worked out fine.
