### ISSUE TITLE
C37.118.2 2011 does not reflect change after new configuration frame accepted

### ISSUE THREAD

**Issue by rajveersinhraol** [GridProtectionAlliance/openPDC#97]
C37.118.2 2011 does not reflect change after new configuration frame accepted.

On resending a new configuration frame, a dialogue box pops up. Agreeing to accept and apply the new configuration frame, the changes are not reflected on the PMU connection  tester UI.

**Comment by ritchiecarroll** [comment]
This seems to be a PMU Connection Tester issue. I am closing this issue off of the openPDC site.

Please feel free re-post the issue on the PMU Connection Tester site:
https://github.com/GridProtectionAlliance/PMUConnectionTester

Thanks!
Ritchie
