### ISSUE TITLE
How to create a "Fake-Source" for simulating  PMU action?

### ISSUE THREAD

**Issue by HowardHsiao** [GridProtectionAlliance/openPDC#99]
Hello, I'm studying at the project. Due to the "lack" resource, I would like to make a program as the PDC's resource. I know the project already have provided the sample for the testing. But, I still want to change some figures (such as timestamp, value ..) for more study.  Thanks!

**Comment by ritchiecarroll** [comment]
The "sample data set" that comes with the openPDC installation includes a captured PMU data file that is used to "simulate" a PMU. Does that work for you?
